# Generated by Django 3.2.5 on 2021-07-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210724_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_pub',
            field=models.DateField(auto_now_add=True, verbose_name='date publication'),
        ),
    ]
